# Generated by Django 4.1.7 on 2023-03-27 05:44

from django.db import migrations
import tests.app.models
import wagtail.blocks
import wagtail.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock()), ('author', wagtailmodelchooser.blocks.ModelChooserBlock(tests.app.models.Author)), ('book', wagtailmodelchooser.blocks.ModelChooserBlock(tests.app.models.Book))], use_json_field=None),
        ),
    ]
